# 1. import library

In [1]:
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans

# 2. import data

In [2]:
df = pd.read_csv('0 Data/clean_data1.csv')
df.drop(['Unnamed: 0'], axis=1, inplace=True)
df.shape

(58693, 7)

In [3]:
df3 = df[['Income', 'Occupation', 'Settlement size']]

# 3. clusters = 2

In [4]:
kmeans = KMeans(n_clusters=2)
kmeans.fit(df)
kmeans.cluster_centers_

array([[ 0.44738552,  0.33630724,  0.30612092,  0.91155096, -0.53031838,
         0.40206795,  0.08924668],
       [ 0.30209717,  0.47051483,  0.44476859,  1.36050396,  0.72258894,
         1.28124623,  1.42800789]])

In [5]:
kmeans = KMeans(n_clusters=2)
kmeans.fit(df3)
kmeans.cluster_centers_

array([[-0.53344535,  0.39734589,  0.08661394],
       [ 0.72225   ,  1.2844309 ,  1.42668645]])

# 4. clusters = 3

In [6]:
kmeans = KMeans(n_clusters=3)
kmeans.fit(df)
kmeans.cluster_centers_

array([[ 0.44923698,  0.33409005,  0.31325271,  0.92558961, -0.54142033,
         0.37365998,  0.02099886],
       [ 0.44794999,  0.65396918,  0.54266081,  1.7973248 ,  1.91783454,
         1.74134923,  1.23727828],
       [ 0.26468979,  0.39698492,  0.38529455,  1.14120105,  0.19806066,
         1.07527738,  1.4588288 ]])

In [7]:
kmeans = KMeans(n_clusters=3)
kmeans.fit(df3)
kmeans.cluster_centers_

array([[-0.54250553,  0.36726849,  0.02511264],
       [ 0.26797263,  1.11777321,  1.43011636],
       [ 2.25052127,  1.84249157,  1.26145606]])

# 5. clusters = 4

In [8]:
kmeans = KMeans(n_clusters=4)
kmeans.fit(df)
kmeans.cluster_centers_

array([[ 2.59994135e-01,  3.91017496e-01,  3.82644251e-01,
         1.13454208e+00,  1.78370556e-01,  1.04657414e+00,
         1.46017007e+00],
       [ 4.54093550e-01,  3.62460322e-01,  2.98040724e-01,
         9.07887644e-01, -9.91426544e-01,  1.51545443e-13,
         6.52811882e-03],
       [ 4.44961706e-01,  6.57756420e-01,  5.47990716e-01,
         1.80582670e+00,  1.94694034e+00,  1.75056315e+00,
         1.27796967e+00],
       [ 4.56067227e-01,  3.11932773e-01,  3.33207135e-01,
         9.58386555e-01, -4.07697742e-03,  8.31462185e-01,
         5.80646642e-14]])

In [9]:
kmeans = KMeans(n_clusters=4)
kmeans.fit(df3)
kmeans.cluster_centers_

array([[ 6.31855447e-02,  9.32280383e-01,  2.83106871e-14],
       [ 3.01632708e-01,  1.14718519e+00,  1.45298312e+00],
       [-9.15138502e-01,  1.54765090e-13,  4.28540470e-02],
       [ 2.74038306e+00,  1.85129890e+00,  1.46372051e+00]])